name: nizvpn
description: Simple VPN using Platform Channel
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  device_apps: ^2.1.1
  dio: ^4.0.0
  flutter_inapp_purchase: 
    git:
      url: https://github.com/mgonzalezc/flutter_inapp_purchase.git
      ref: fix/mindapps_fix
  app_tracking_transparency: ^2.0.2+1
  google_fonts: ^2.1.0
  in_app_review: ^2.0.4
  in_app_update: ^3.0.0
  introduction_screen: ^3.0.0 
  line_icons: ^2.0.1
  lottie: ^1.2.1
  ndialog: ^4.1.0
  package_info: ^2.0.2
  provider: ^6.0.1
  pull_to_refresh_flutter3: ^2.0.1
  share: ^2.0.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  snapping_sheet: ^3.1.0
  get: ^4.6.5
  card_swiper: ^2.0.4
  intl: ^0.17.0
  easy_logger: ^0.0.2
  flutter_inappwebview: ^5.4.4+3
  #屏幕适配
  flutter_screenutil: ^5.5.3
  #  事件总线--EventBus
  event_bus: ^2.0.0
  fluttertoast: ^8.0.8
  #数据json解析（官方框架）
  json_annotation: ^4.4.0 # null safe
  json_serializable: ^6.1.1 # null safe
  #网络响应日志打印框架
  pretty_dio_logger: ^1.2.0-beta-1
  #普通日志打印框架  https://github.com/leisim/logger
  logger: ^1.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/icons/"
    - "assets/images/banner/"
    - "assets/icons/flags/"
    - "assets/languages/"
    - "assets/animations/"
  fonts:
    - family: NerdVPNIcon
      fonts:
        - asset: assets/fonts/NerdVPNIcon.ttf
